---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBYq+A4zRwHnj/mDEZT7ECRLea7nYH3OC+CdCjtDkr5hVFtuMv4seVhvUuJVA+knCexvxVwySTHbK20mIETMGl257Lp5FT4owDhSNyflP/9K2K7wui4zaxEJaIuw5ypsvJBfyb3HDYU3n3cqjrkl2qTzEI5Som589s3/e95yZFKWNgnWHgn9aloBxFwy8MOHtE3UBPOXwmzFBtXAccCM3iC+jhZ3TOCrFjZtYBDSX1CI+P9bdx0swzoHNnucPZ6LWubekiJz/ia0WocFg3wFa471EW1b2icv7VN1JzpOJnTtat9AYeVwKnbF85IXijC617S7Qeg1UScP//jFsT72BuUD0Flfgz1Pu3xY7VxulclUd9LhlxftB8Ad1hmbP1jOqFTMe80R0mU+Lz4SRVrwCbkb4GOmKi6f5zV4S3nm8cSand5/P99LIN0Te/2n/gzAP9hXyj4O4LsGCT/R4SNtiJU3Ovw2n+JpsuOrVA/tjqvUSzcyiS4bHeXDvPaJKbToX+t5Jtat22CXEkVst0YgfkfRCUUzD2PITzC7c6gae5QsJ9kNvhXNo7s21GoO2ZiqQ8RXlOSRDO6y3F9gvfxURBBB+sJl+gWMC/YyXAXvNuMkO5PDbJ5h+z+TT/HPD3z4iYcj3EXIO7Ba2OprVW7eFbbJB9neIqTgW+inxy6ZFDZOOx00YWmZ9YSC5zyQ8UuOQoH6mamT6Do
    admin-user: AgBeFKNv0DC7jJju3IFp5LJf0r4axpTYQuh7hN4c8TkiDqMfc382ist7jZlBUSOHaTPb+o2rbJy+1aqjFe4+W3RHt4mZl9ciStbODeMo7XwiRLaZ1YpcJ5xomPPrF8lDM8Goasr7umfIyDAMxg0USg2FSVrn+61xbfnZTbxQrxUw5aSa9xav2xcsojVDV5ztxyItemvCCthgTBmgznC+Eu8B8xSW9MCnhpRXrhwcQV+2+iD7L3BtfaUZwXxnb8xNzdn8Y3jUylWFgqIQDJ1CzwqGFRZGOwW8Pgswb+1lxlw7j4x3AaOlx+Zas7AxBUD+P/A0xbdNhGiA8WQo3i2+yiMH3WkcIk7NNWaiHA/gNzdWyPXT5xz8qC4Os5wSfRn1tW8XE90Dz/NSg/xbtuBrq4x0deSzz+HQE8BzpAcoQ5i2g89OU08WiL1qWKVl8AWiyEPw58I5C9E/NY/Sqm833/PbOMFhuh4qXkdCMshCVe3aNcS0GMyRY84zZ8ZJZto1WrtHEOK1WjAshbjlajr0vznPDXW6EfwiG/fXYzsFsHve94hH9R9HQ19m8d4e2ZSoa6SQ0LSgw3T8F1eXtaZMwj9bxmo4LePAsJ2SKIH40fqmrriwRM/M96L1afkTOB0zQgESLl7aDE0HyaK61Hf5HkLgrvkDXjHaA4qmxPIKZYp+KfyZcTKDmySt40kB/Y7cB7WOC/qenQ==
  template:
    metadata:
      name: grafana-admin-password
      namespace: monitoring
