service:
  main:
    type: ClusterIP
    ports:
      http:
        port: 3000
ingress:
  main:
    enabled: true
    className: traefik
    hosts:
      - host: homepage.codexasystems.net
        paths:
          - path: /
            pathType: Prefix

# --- No persistence needed ---

persistence:
  config:
    enabled: false

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "homepage.codexasystems.net"   # <-- replace with your actual node IP

  - name: HOMEPAGE_VAR_PLEX_TOKEN
    valueFrom:
      secretKeyRef:
        name: homepage-plex-token
        key: PLEX_TOKEN

  - name: HOMEPAGE_VAR_TECHNITIUM_TOKEN
    valueFrom:
      secretKeyRef:
        name: homepage-technitium-token
        key: TECHNITIUM_TOKEN

  - name: HOMEPAGE_VAR_GRAFANA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: grafana-admin-password
        key: admin-password


enableRbac: true
serviceAccount:
  create: true

config:

  kubernetes:
    mode: cluster

  settings:
    title: PA Cluster
    description: My awesome homepage
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    blur: xl # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
    saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
    brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
    opacity: 50 # 0-100
    layout:
      - PIDNS:
          style: row
          columns: 2
      - PAKUBE Monitor:
          style: row
          columns: 2
      - Widgets:
          style: row
          columns: 2


  services:
    - PIDNS:
        - Pi 1 Temp:
            widget:
              type: iframe
              name: Pi 1 Temp
              src: "http://192.168.1.10:4000/d-solo/ad6wzbp/pidns-temp?orgId=1&from=now-2h&to=now&panelId=panel-1&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

        - Pi 2 Temp:
            widget:
              type: iframe
              name: Pi 2 Temp
              src: "http://192.168.1.10:4000/d-solo/ad6wzbp/pidns-temp?orgId=1&from=now-2h&to=now&panelId=panel-2&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

        - PIDNS Network:
            widget:
              type: iframe
              name: PIDNS Network
              src: "http://192.168.1.10:4000/d-solo/adwq628/Networking?orgId=1&from=now-2h&to=now&panelId=panel-1&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

        - PIDNS2 Network:
            widget:
              type: iframe
              name: PIDNS2 Network
              src: "http://192.168.1.10:4000/d-solo/adwq628/pidns-temp?orgId=1&from=now-2h&to=now&panelId=panel-2&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

        - PIDNS CPU:
            widget:
              type: iframe
              name: PIDNS CPU
              src: "http://192.168.1.10:4000/d-solo/ad2xjfd/pidns-temp?orgId=1&from=now-6h&to=now&panelId=panel-7&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

        - PIDNS Memory:
            widget:
              type: iframe
              name: PIDNS memory
              src: "http://192.168.1.10:4000/d-solo/ad2xjfd/pidns-temp?orgId=1&from=now-6h&to=now&panelId=panel-8&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

    - PAKUBE Monitor:
        - PAKube CPU Load:
            widget:
              type: iframe
              name: PAKUBE trend
              src: "http://192.168.1.10:4000/d-solo/ad2xjfd/new-dashboard?orgId=1&from=now-1h&to=now&timezone=utc&var-datasource=prometheus&var-cluster=$__all&var-instance=192.168.1.10:9100&panelId=panel-3&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

        - PAKube2 CPU Load:
            widget:
              type: iframe
              name: PAKUBE2 trend
              src: "http://192.168.1.10:4000/d-solo/ad2xjfd/new-dashboard?orgId=1&from=now-1h&to=now&timezone=utc&var-datasource=prometheus&var-cluster=$__all&var-instance=192.168.1.10:9100&panelId=panel-4&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

        - Cluster freq:
            widget:
              type: iframe
              name: Pi 1 Temp
              src: "http://192.168.1.10:4000/d-solo/ad2xjfd/new-dashboard?orgId=1&from=now-6h&to=now&timezone=utc&var-datasource=prometheus&var-cluster=$__all&var-instance=192.168.1.10:9100&panelId=panel-1&refresh=5s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

        - Cluster memory:
            widget:
              type: iframe
              name: Pi 1 Temp
              src: "http://192.168.1.10:4000/d-solo/ad2xjfd/new-dashboard?orgId=1&from=now-6h&to=now&timezone=utc&var-datasource=prometheus&var-cluster=$__all&var-instance=192.168.1.10:9100&panelId=panel-2&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

        - PAKUBE Network:
            widget:
              type: iframe
              name: PIDNS2 Network
              src: "http://192.168.1.10:4000/d-solo/adwq628/pidns-temp?orgId=1&from=now-2h&to=now&panelId=panel-3&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

        - PAKUBE2 Network:
            widget:
              type: iframe
              name: PIDNS2 Network
              src: "http://192.168.1.10:4000/d-solo/adwq628/pidns-temp?orgId=1&from=now-2h&to=now&panelId=panel-4&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

        - PAKUBE CPU Temp:
            widget:
              type: iframe
              name: PIDNS2 Network
              src: "http://192.168.1.10:4000/d-solo/ad2xjfd/pidns-temp?orgId=1&from=now-2h&to=now&panelId=panel-9&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no
        - PAKUBE2 CPU Temp:
            widget:
              type: iframe
              name: PIDNS2 Network
              src: "http://192.168.1.10:4000/d-solo/ad2xjfd/pidns-temp?orgId=1&from=now-2h&to=now&panelId=panel-6&refresh=10s&hideLogo=true"
              classes: h-52
              referrerPolicy: same-origin
              allowFullscreen: false
              loadingStrategy: eager
              allowScrolling: no

    - Widgets:
        - Grafana:
            icon: grafana.png
            href: http://192.168.1.9:4000
            decription: grafan instance
            widget:
              type: grafana
              version: 2 # optional, default is 1
              alerts: alertmanager # optional, default is grafana
              url: http://192.168.1.9:4000
              username: admin
              password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"

        - Prometheus:
            icon: prometheus.png
            widget:
              type: prometheusmetric
              url: http://prometheus-stack-kube-prom-prometheus.monitoring:9090
              refreshInterval: 10000
              metrics:
                - label: Active Alerts
                  query: alertmanager_alerts{state="active"}
                - label: CPU Usage
                  query: round(avg(1 - rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100, 0.1)
                  format:
                  type: percent
                - label: Memory Used
                  query: node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes
                  format:
                    type: bytes

        - Plex:
            icon: plex.png
            href: http://192.168.1.10:32400/web
            description: Media server
            widget:
              type: plex
              url: http://192.168.1.10:32400
              key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"

        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true

        - Technitium DNS:
            icon: technitium.png
            href: http://192.168.1.6:5380
            description: Local DNS server
            widget:
              type: technitium
              url: http://192.168.1.6:5380
              key: "{{HOMEPAGE_VAR_TECHNITIUM_TOKEN}}"


    - Home-Automation:
        - homeassistant:
            icon: homeassistant.png

              # this might need the server running in back ground??
#git ops sync test - 23/09/26
