---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: homepage
spec:
  encryptedData:
    admin-password: AgA9mk7CdoqBMlIFCFwB7Cnh8dtCd6lMJ8FVJCCzzB0NJrn6SRL+erVq34Igj0DOeejYDmtyQMKCpifMZ16a531/p/Bn8vVNPfcJ78Z1tjzIr07kW6Fy82grA+Kxa2833pTsQmaE/eUTbX0k6wEU0ZRieeGAwX8ofv3L78fWLBVFIefpcTmhowV2G1oK9+w5uWNyDQt+G6HjmIZ3YXr0ubOVGaE61TtcKUwY/9UE7WU/zTC/42rKwgWH3oameb2kk+K/mUP/zTMVSgYO9OQUutUoWfT9ghpI+L+KEJE/OBazrAp8R48ZMmS/ZeodamLdVEx/HMGQtACPZQC4WHFJRDxVAlo3/ypGV12QvauwwxUT7CYFxPMw8eaan8uHoReHAxMVaolQP9s5miLkn5HsEQsP3Vg5aSfhAv567KMCTBN3HUuylqSFMfajYUdxZQHTPnzXjN53Av5cwU//IlJu63MD4fR7QppPVJPVzFPwY+rRlPIM/w4wDnRx30ZoYvg1M2VNlDuLLhMOjbKRJmggwhTnn7wTNx/66KgZRbElg7nMENfGhhrX6On5zKtv6IGv1pKTCXzyW/weS0yYVOQ39fikglpGDQix9XvDtNEFPX41Ql6tbD9wzCDA7d682FE2Iu8qQ19wj5vKvOoxemsIOpjsIPZJqgMM7w7ViFjin8Lg/SjrroDEvlkn0WWOLf0KCcULOE1qb+Ki
    admin-user: AgCDu2Eyd3HeKLaH/evDp1dnRVD7yKkdJqvM2ABtYFwmr7Tfqsr/2OUV6t1Y/O8AZK2KDGIeel3PEytBMCCn6+3ahF3KMoUOaMW5nzOa7LEu26P/ktOpC27ZD+Nf3K03aTcGv2nc/mrrpMbdJAzlnzebBl8B5p1jHOFWTR5HWbVSzaF9ykIYWwajhA/oNBDnO8xExrVrET52oQFS9OJgQeO8G0imaXbc4kPGSrQkSZqrt3YCsqp6HTdrhcN2+3O4240AEQzeryrVkypAMKBaG7dska/WewWc+2apFLKmaO27EVKjrbvehBLv64PeWNifjfSNgTAZpmjtfaSDWpiIUEAuOwCrKDyVoL7n++CuDhueFQLc5nJcIvrvLr5LOu0a2WN1QA7BC8dcV/k/RnvLxJcOGNve4vc993aK+kqP/pIB79KOBzlKsEUr34Aau1/ORcO60kkMc9nFmEyBPTbOCrUXeSo4O6haj4ytv/wanZramCoKqjoGwhjEdcLTZ7KIf+K0eWzY9cWohPHHZAYAMTXqkbVm7liJtZw9ORH1fig0Dvme+X+3/xuKOuXu9O99+QgoBxzcrXUkOQ3Am1bEKi9J4gDZkXaznL2DLClEd/x3iZVsEDodglpbL39LzZVkFyCj468Zh5Tsw1QfqbA5au9o85DkTUPy8hs9K8e+Hjo+NxNOTSydnZs+An7QPJN2AvLple8TmA==
  template:
    metadata:
      name: grafana-admin-password
      namespace: homepage
