grafana:
  service:
    type: LoadBalancer
    port: 4000
  admin:
    existingSecret: "grafana-admin-password"
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path
    accessModes: ["ReadWriteOnce"]
    size: 1Gi
  grafana.ini:
    security:
      allow_embedding: true
    feature_toggles:
      publicDashboards: true
      renderAuthJWT: false
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Viewer
    rendering:
      server_url: http://localhost:8081/render
      callback_url: http://localhost:3000/
      renderer_token: "273e031937b1fa7a22da0e2c6ac55db6a5627b316f5f4b75c66ebc60ed85b439"
  extraContainers: |
    - name: grafana-renderer
      image: grafana/grafana-image-renderer:latest
      ports:
        - name: renderer
          containerPort: 8081
          protocol: TCP
      env:
        - name: ENABLE_METRICS
          value: "false"
        - name: AUTH_TOKEN
          value: "273e031937b1fa7a22da0e2c6ac55db6a5627b316f5f4b75c66ebc60ed85b439"

prometheus:
  service:
    type: LoadBalancer
    port: 9090
    targetPort: 9090
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'pidns'
        static_configs:
          - targets: ['192.168.1.6:9100', '192.168.1.7:9100']


kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
