apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-example-com-tls
    additionalArguments:
      - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=600s"
      - "--entryPoints.websecure.transport.respondingTimeouts.idleTimeout=600s"
